### ISSUE TITLE
Throws a thousand errors when compiling

### ISSUE THREAD

**Issue by roro47** [ImperialCollegeLondon/M4P33#1]
Some issue me and some other people are having now. Is there any special configuration?

**Comment by Multramate** [comment]
Same here. I'm getting lots of
```
excessive memory consumption detected at 'replace' (potential solution: increase memory consumption threshold)
```
There seems to be a Zulip Chat thread on this already, but the solution seemed to be "have you turned it off and on again"?

**Comment by roro47** [comment]
Restart the whole lean server?

**Comment by roro47** [comment]
> Same here. I'm getting lots of
> 
> ```
> excessive memory consumption detected at 'replace' (potential solution: increase memory consumption threshold)
> ```
> 
> There seems to be a Zulip Chat thread on this already, but the solution seemed to be "have you turned it off and on again"?


Restart the lean server?

**Comment by roro47** [comment]
> Same here. I'm getting lots of
> 
> ```
> excessive memory consumption detected at 'replace' (potential solution: increase memory consumption threshold)
> ```
> 
> There seems to be a Zulip Chat thread on this already, but the solution seemed to be "have you turned it off and on again"?

Accurate. I run the command "Lean: restart" in vscode, and everything's working now for me.
